MedLib/MedLib/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

MedLib/main/urls.py
from django.conf.urls import url

from . import views


app_name = 'main' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),
    #url for login-page:
    url(r'^login$', views.login, name='login'),
    #url for signup-page:
    url(r'^signup$', views.signup, name='signup'),

    #url to log in a user:
    url(r'^log_req$', views.logInReq, name='login_req'),
    
    #url for create-user:
    url(r'^register_user$', views.register, name='register_user'),

    #url for logged-in:
    #url(r'(?P<pk>[0-9]+)/logged_in/$',views.LoggedIn.as_view(),name='loggedin'),

    #url for logout:
    url(r'^logout$', views.logout, name='logout'),

    #url to search a topic:
    url(r'^search$', views.search, name='search'),

    url(r'^search1$', views.search1, name='search1'),

    #url to search a topic:
    url(r'^search_checkup$', views.search_checkup, name='search_checkup'),

    url(r'^blood-type$', views.blood_type, name='blood_type'),

    url(r'^blood-donors-search$', views.blood_search, name='blood_search'),

    url(r'^quest$', views.quest, name='quest'),

    url(r'^doctors$', views.doc_list, name='doc_list'),
    
    url(r'^question$', views.question, name='question'),
]

MedLib/main/models.py
from django.db import models

class Users(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=120,unique=True)
    pwd= models.CharField(max_length=80)
    age= models.IntegerField()
    sex=models.CharField(max_length=8)
    latitude=models.CharField(max_length=50,default="")
    longitude=models.CharField(max_length=50,default="")
    address=models.CharField(max_length=100,default="")
    blood=models.CharField(max_length=8,default="")
    blood_type=models.CharField(max_length=8,default="")
    phone=models.CharField(max_length=20,default="9508233223")
            
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.IntegerField(default=0) #simple=0 org=1
    #def __str__(self):
    #    return self

class History(models.Model):
    email = models.CharField(max_length=120)
    dis_name = models.CharField(max_length=120)
    dis_severity = models.CharField(max_length=120)
    dis_probname = models.CharField(max_length=120)
    dis_hint = models.CharField(max_length=120)
    dis_time = models.CharField(max_length=120)


"""
class Topic(models.Model):
    #tags = models.ForeignKey(Tag, on_delete = models.CASCADE)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    topic_text = models.CharField(max_length=250)
    topic_desc=models.CharField(max_length=700,default="")
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.topic_text


class Tag(models.Model):
    tag_name= models.CharField(max_length=50)
    tag_desc=models.CharField(max_length=500,default="")
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    def __str__(self):
        return self.tag_name

class Opinion(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    opinion_text=models.CharField(max_length=500)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    foragainst=models.IntegerField(default=0) #for=1 against=0
    def __str__(self):
        return self.user.user_name
"""

MedLib/main/forms.py
from django import forms

class SignupForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.CharField(max_length=120)
    pwd = forms.CharField(max_length=80)
    age = forms.IntegerField()
    sex = forms.CharField(max_length=7)
    address = forms.CharField(max_length=100)
    blood = forms.CharField(max_length=8)
    blood_type = forms.CharField(max_length=8)
    phone = forms.CharField(max_length=20)


class LoginForm(forms.Form):
    email=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

"""
class AddTopicForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    topic_desc=forms.CharField(max_length = 700)
    tag_text=forms.CharField(max_length = 250)

class AddOpinionForm(forms.Form):
    opinion_text=forms.CharField(max_length = 500)
    topic = forms.CharField(max_length = 5)
"""

class SearchForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    #symptom=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,required=False)

MedLib/main/views.py
from django.shortcuts import render,get_object_or_404
from django.core.exceptions import ObjectDoesNotExist #This may be used instead of Users.DoesNotExist
from django.http import HttpResponse,HttpResponseRedirect
from .medget import medget
from django.views import generic
import re
import medplace
from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse
import ast
import datetime
import time

from .models import Users, History
from main.forms import SignupForm,LoginForm,SearchForm#,AddTopicForm,AddOpinionForm,

ob=medget()
j = []


def index(request):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=Users.objects.get(pk=uid)
            hist = []
            hist.extend(History.objects.filter(email=user.email).values('dis_name', 'dis_severity', 'dis_time'))
            #return HttpResponse(hist)
            return render(request, 'Temp/logged.html',{'user_id':user, 'history':hist})
        except Users.DoesNotExist:
            return HttpResponse("UserName not found")
    else:
        return render(request, 'Temp/main.html')

def login(request):
    return render(request, 'Temp/login.html')

def signup(request):
    return render(request, 'Temp/signup.html')

def search_checkup(request):
    return render(request, 'Temp/search_checkup.html')


def blood_type(request):
    return render(request, 'Temp/blood_type.html')

def blood_search(request):
    if request.method == 'POST':
        location = request.POST['location']
        loc_dict = ast.literal_eval(location)
        loc_dict1 = {}
        loc_dict1['lat'] = loc_dict['latitude']
        loc_dict1['lng'] = loc_dict['longitude']

        plac = medplace.get_places(lat_lng=loc_dict1, doctor_type='blood bank')
        #return HttpResponse("hey" + str(plac))
        
    
        #checklist = topic.cleaned_data.get('symptom')
        checklist = []
        try:
            checklist.append(request.POST['blood1'])
        except:
            pass
        try:
            checklist.append(request.POST['blood2'])
        except:
            pass
        try:
            checklist.append(request.POST['blood3'])
        except:
            pass
        try:
            checklist.append(request.POST['blood4'])
        except:
            pass
        try:
            checklist.append(request.POST['blood5'])
        except:
            pass
        try:
            checklist.append(request.POST['blood6'])
        except:
            pass
        try:
            checklist.append(request.POST['blood7'])
        except:
            pass
        #return HttpResponse(checklist)
        #k = Users.objects.filter(blood='O+', blood_type='YES').values('email', 'name', 'phone', 'age', 'blood', 'blood_type', 'address')
        #for l in k:
        #    return HttpResponse('hey' + str(l['email']) + str(l['name']) + str(l['phone']))
            #return render(request, 'Temp/symtoms.html', {"list": li,"len":l})
         
        user_model = []
        for i in checklist:
            user_model.extend(Users.objects.filter(blood=i, blood_type='YES').values('email', 'name', 'phone', 'age', 'blood', 'blood_type', 'address'))
            #return HttpResponse(user_model)
        
            #user_model.append(user_model))
            #return HttpResponse(user_model)
        
        #return HttpResponse("hey" + str(user_model))
        
    return render(request, 'Temp/blood_search.html', {"user_list": user_model,"blood_bank": plac, }) 


def search(request):
    if request.method == 'POST':
        topic=SearchForm(request.POST)
        if topic.is_valid():

            #t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))
            top_li = Topic.objects.all()
            li=[]
            for t in top_li:
                if re.search(topic.cleaned_data.get('topic_text'),t.topic_text,re.IGNORECASE):
                    li.append(t)
            if request.session.has_key('user_id'):
                uid = request.session['user_id']
                user = Users.objects.get(pk=uid)
                return render(request, 'Temp/searchresults.html', {'user_id':user,"list": li})
            else:
                return render(request, 'Temp/searchresultL.html', {"list": li})
        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")

def search1(request):
    if request.method == 'POST':
        topic=SearchForm(request.POST,initial={"topic_text": "c"})
        if topic.is_valid():
            sim_str=topic.cleaned_data.get('topic_text')
            checklist=sim_str.split(",")
            #checklist = topic.cleaned_data.get('symptom')

            try:
                checklist.append(request.POST['symptom1'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom2'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom3'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom4'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom5'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom6'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom7'])
            except:
                pass
            #return HttpResponse(checklist)

            li=ob.search_symptoms(checklist)
            l = len(li)
            return render(request, 'Temp/symtoms.html', {"list": li,"len":l})


            #return HttpResponse((' ').join(li))
            #t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))

        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")



def register(request):
    if request.method == 'POST':
        signup=SignupForm(request.POST)
        if signup.is_valid():
            p=Users(
                name=signup.cleaned_data.get('name'),
                email=signup.cleaned_data.get('email'),
                pwd=signup.cleaned_data.get('pwd'),
                age=signup.cleaned_data.get('age'),
                sex=signup.cleaned_data.get('sex'),
                address=signup.cleaned_data.get('address'),
                blood=signup.cleaned_data.get('blood').upper(),
                blood_type=signup.cleaned_data.get('blood_type').upper(),
                phone=signup.cleaned_data.get('phone'),
                
            )
            p.save()
            request.session['user_id'] = p.id
    return HttpResponseRedirect(reverse('main:index'))

def logInReq(request):
    if request.method == 'POST':
        log=LoginForm(request.POST)
        if log.is_valid():
            try:
                user=Users.objects.get(email=log.cleaned_data.get('email'),pwd=log.cleaned_data.get('pwd'))
                request.session['user_id'] = user.id
                return HttpResponseRedirect(reverse('main:index'))
            except Users.DoesNotExist:
                return HttpResponse("WRONG USERNAME OR PASSWORD")

"""
class LoggedIn(generic.DetailView):
	model = Users
	template_name = 'Temp/logged.html'
	context_object_name = 'user_id'
"""

def quest(request):
    global ob
    if request.method == 'POST':
        l=request.POST['len']
        checklist=[]
        for i in range(int(l)):
            try:
                checklist.append(request.POST['symptom'+str(i)])
            except:
                pass
        #return HttpResponse(checklist)
        if request.session.has_key('user_id'):
            uid = request.session['user_id']
            try:
                user = Users.objects.get(pk=uid)
            except ObjectDoesNotExist:
                HttpResponse("Object not found")

            age = 21#int(user.age)
            sex = 'male'#user.sex.lower()
            ob.get_data(sex,age)
            lis=[]
            for i in checklist:
                dic={}
                dic['id']=i
                dic['status']='present'
                lis.append(dic)
                dic=None

            #ob.add_symptoms(lis)
            request.session['lis'] = lis
            return HttpResponseRedirect(reverse('main:question'))
            #return HttpResponse(a)
        #ob.get_questions()

def question(request):
    global ob
    #global j
    #j +=1
    i = []
    if request.session.has_key('lis'):
        i = request.session['lis']
        try:
            del request.session['lis']
        except:
            pass
        ob.add_symptoms(i)
        a = ob.get_question()
        return render(request, 'Temp/question.html', {"ques_dict": a})
        #return HttpResponse(a)
    elif not ob.check_risk():
        i = {}
        #id = request.POST.get('id')
        if request.POST.get('yes'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'present'
        elif request.POST.get('no'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'absent'
        elif request.POST.get('dont'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'unknown'
    
        a = []
        a.append(i)
        ob.add_symptoms(a)
        a = ob.get_question()
        #j = i
        return render(request, 'Temp/question.html', {"ques_dict": a})
    else:
        result = {}
        uid = request.session['user_id']
        user = Users.objects.get(pk=uid)
        result = ob.get_result()
        History(
            email=user.email,
            dis_name=result['name'],
            dis_severity=result['severity'],
            dis_probname="",
            dis_hint=result['hint'],
            dis_time = str(datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S')),
        ).save()

MedLib/main/templates/Temp/blood_type.html
                   
<!DOCTYPE html> {% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/imagehover.min.css' %}" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                <a class="navbar-brand" href="/">MEDICAL LIBRARY</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/search_checkup">CHECK-UP NOW</a></li>
                    
                    <li class="btn-trial"><a href="/">Profile Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
<br><br>
<div class="container">
<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
 <div class="mail-box">
                   <aside class="lg-side">
                      <div class="inbox-head" style="border-top-left-radius:900px;border-top-right-radius: 900px" >
                         <center><h3>Search Blood Donors</h3>
                         <form class="form" method="POST" action="{% url 'main:blood_search' %}"><!--Not applied yet -->
                        {% csrf_token %}       <br>                
                        <input class="btn btn-compose" type="submit"  style="width: 100px" value="Search" >
                        <br></center>
                        <br>
                        <div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
            <div class="panel panel-default" style="color: #000">
                <!-- Default panel contents -->
                <div class="panel-heading">Choose a Blood Group</div>
            
                <!-- List group -->
                <ul class="list-group">
                    <li class="list-group-item">
                        O+
                        <div class="material-switch pull-right">
                            <input id="1" name="blood1" value="O+" type="checkbox"/>
                            <label for="1" class="label-default"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        O-
                        <div class="material-switch pull-right">
                            <input id="2" name="blood2" value="O-" type="checkbox"/>
                            <label for="2" class="label-primary"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        A+
                        <div class="material-switch pull-right">
                            <input id="3" name="blood3" value="A+" type="checkbox"/>
                            <label for="3" class="label-success"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        A-
                        <div class="material-switch pull-right">
                            <input id="4" name="blood4" value="A-" type="checkbox"/>
                            <label for="4" class="label-info"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        B+
                        <div class="material-switch pull-right">
                            <input id="5" name="blood5" value="B+" type="checkbox"/>
                            <label for="5" class="label-warning"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        B-
                        <div class="material-switch pull-right">
                            <input id="6" name="blood6" value="B-" type="checkbox"/>
                            <label for="6" class="label-danger"></label>
                        </div>
                    </li>

                    <li class="list-group-item">
                        AB+
                        <div class="material-switch pull-right">
                            <input id="8" name="blood7" value="AB+" type="checkbox"/>
                            <label for="8" class="label-default"></label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        AB-
                        <div class="material-switch pull-right">
                            <input id="7" name="blood7" value="AB-" type="checkbox"/>
                            <label for="7" class="label-default"></label>
                        </div>
                    </li>
                </ul>
            </div>            
        </div>
    </div>
</div>
  <input type="hidden" name="location" id="location" value="{"ip" : "47.31.14.117", "country_code" : "IN", "country_name" : "India", "region_code" : "DL", "region_name" : "National Capital Territory of Delhi", "city" : "Delhi", "zip_code" : "", "time_zone" : "Asia/Kolkata", "latitude" : "28.6667", "longitude" : "77.2167", "metro_code" : "0", }"><br>

                    </form>
                    
                              </div>
                          </form>
                      </div>
                    
                  </aside>
              </div>
</div>
</body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    //console.log("23");    
   // alert("hey");
    var l = "";
    //console.log(l);
    //alert("hey2");
        $.getJSON("https://freegeoip.net/json/", function(result){
            l = l + "{";            
            $.each(result, function(i, field){
            	l = l + "\"" + i + "\" : " + "\"" + field + "\", ";
                        
            });
           // alert("hey"+l);
            //alert("hey");
            l = l + "}";
            $('#location').val(l);
            //alert("hey"+l);
        });
    
});
</script>

MedLib/main/templates/Temp/get_result.html
<!DOCTYPE html> {% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/imagehover.min.css' %}" type="text/css" />
</head>

<<<<<<< HEAD
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                <a class="navbar-brand" href="/">HEALTH MEDLIB</a>
            </div>
            
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/search_checkup">CHECK-UP NOW</a></li>

                    <li class="btn-trial"><a href="/">Profile Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br><br>
    <br>
    <div class="container">
        <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
        <div class="mail-box">
            <aside class="lg-side">
                <div class="inbox-head">
                    <br>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                              <img src="{% static 'img/doc.png' %}" style="max-height: 530px" alt="" />
                            </div>
                            <div class="col-sm-6">
                                <div class="panel panel-warning" style="color: #000">
                                    <!-- Default panel contents -->
                                    <div class="panel-heading">Your Result </div>
                                    <div style="padding: 20px;text-align: justify">
                                       <b> Disease : </b>  {{ result.name }} <br>
                   <b>Severity :</b> {{ result.severity }}<br>
                  <b> Suggestion : </b>{{ result.probname }}
                    {{ result.hint }}<br>
                    <form class="form" method="POST" action="{% url 'main:doc_list' %}"><!--Not applied yet -->
                        {% csrf_token %}
                        
                        <br>
                        <input type="submit"  class="btn btn-primary" name="find_doctor" id="find_doctor" value="GET NEARBY DOCTORS"><br>
                        <input type="hidden" name="location" id="location" value="{"ip" : "47.31.14.117", "country_code" : "IN", "country_name" : "India", "region_code" : "DL", "region_name" : "National Capital Territory of Delhi", "city" : "Delhi", "zip_code" : "", "time_zone" : "Asia/Kolkata", "latitude" : "28.6667", "longitude" : "77.2167", "metro_code" : "0", }"><br>
                        <input type="hidden" name="doctor_type" id="doctor_type" value="{{ result.hint }}">               
                    </form>


                             </div>
                            </div>
                        </div>
                    </div>

                    </form>

                </div>
                </form>
        </div>

        </aside>
    </div>
    </div>
      <div id = "geolocat">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    //console.log("23");    
    //alert("hey");
    var l = "";
    //console.log(l);
    //alert("hey2");
        $.getJSON("https://freegeoip.net/json/", function(result){
            l = l + "{";            
            $.each(result, function(i, field){
            	l = l + "\"" + i + "\" : " + "\"" + field + "\", ";
                        
            });
            l = l + "}";
            $('#location').val(l);
            //alert("hey"+l);
        });
    });
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" asnyc></script>>
</body>

</html>

MedLib/main/templates/Temp/login.html
<!DOCTYPE html> {% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/imagehover.min.css' %}" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                <a class="navbar-brand" href="/">HEALTH MEDLIB</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Home</a></li>
                    <li><a href="/">About</a></li>
                    <li><a href="/login">Old User</a></li>
                    <li><a href="/signup">New User</a></li>
                    <li class="btn-trial"><a href="/">It's Free  </a></li>
                </ul>
            </div>
        </div>
    </nav>
<br><br><br>
<div class="container">
      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'main:login_req' %}">
			{% csrf_token %} 
            <div class="form-group">
              <input type="text" class="abc" name="email" placeholder="UserName" required>
            </div>
            <div class="form-group">
              <input type="password" class="abc" name="pwd" placeholder="Password" required>
            </div>
            <div class="form-group">
              <button class="abcbut">Sign In</button>
              </div>
          </form>
      </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" asnyc></script>
  </body>
</html>